version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    image: pokemon-viewer-backend:latest
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}

  db:
    image: postgres:14.5
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}